<?php /* Smarty version 2.6.11, created on 2014-03-15 08:43:39
         compiled from mods/users/_reg.html */ ?>
<?php echo '<h2>Sign up</h2><div class="sing-title">The simple way to connect and share with your <br />LDS friends.  <font color="#808080">Anyone can join!</font></div><div class="sbox01"><img src="/i/icon01.png" alt="" /><p>Share thoughts, news, photos and videos</p></div><div class="sbox01"><img src="/i/icon02.png" alt="" /><p>Connect with your ward/stake members</p></div><div class="sbox01"><img src="/i/icon03.png" alt="" /><p>Keep in touch with your friends away on a mission</p></div><div class="reg-form"><table><tr><td align="right"><label>First name:</label></td><td><p><input class="txt" id="rname" type="text" value="" /></p></td></tr><tr><td align="right"><label>Last name:</label></td><td><p><input class="txt" id="rlname"  type="text" value="" /></p></td></tr><tr><td align="right"><label>You are:</label></td><td><span class="niceform" style="margin-bottom:0px"><select id="rgender" size="1"><option>Select</option><option value="1">Male</option><option value="2">Female</option></select></span></td></tr><tr><td align="right"><label>When were you born?</label></td><td><span class="niceform" style="margin-bottom:0px;"><select id="bmonth" size="1" style="width:50px;"><option></option>';  $_from = $this->_tpl_vars['mm']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['bmonth'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['bmonth']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['k'] => $this->_tpl_vars['i']):
        $this->_foreach['bmonth']['iteration']++;
 echo '<option value="';  echo $this->_tpl_vars['k'];  echo '">';  echo $this->_tpl_vars['i'];  echo '</option>';  endforeach; endif; unset($_from);  echo '</select></span><span class="niceform" style="margin-bottom:0px;"><select id="bday" size="1" style="width:50px;"><option></option>';  $_from = $this->_tpl_vars['dd']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['k'] => $this->_tpl_vars['i']):
 echo '<option value="';  echo $this->_tpl_vars['k']+1;  echo '">';  echo $this->_tpl_vars['i'];  echo '</option>';  endforeach; endif; unset($_from);  echo '</select></span><span class="niceform" style="margin-bottom:0px;"><select id="byear" size="1" style="width:50px;"><option></option>';  $_from = $this->_tpl_vars['yy']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['k'] => $this->_tpl_vars['i']):
 echo '<option value="';  echo $this->_tpl_vars['i'];  echo '">';  echo $this->_tpl_vars['i'];  echo '</option>';  endforeach; endif; unset($_from);  echo '</select></span></td></tr><tr><td align="right"><label>Your email:</label></td><td><p><input class="txt" id="remail" type="text" value="" /></p></td></tr><tr><td align="right"><label>Re-enter email:</label></td><td><p><input class="txt" id="remail2" type="text" value="" /></p></td></tr><tr><td align="right"><label>Password:</label></td><td><p class="pass"><input class="txt" type="password" id="rpass" value="" /></p></td></tr><tr><td>&nbsp;</td><td><div class="but-box" style="margin-top:-3px"><span><a href="javascript:void(0);" id="reg_btn">Sign Up</a></span></div></td></tr></table><div id="reg_errs" class="error_box" style="display: none; padding:5px;"></div></div>'; ?>